title: StopInsect — уничтожение насекомых
email: monitoringe@gmail.com
description: >-
  Компания «Stopinsekt» более 10 лет оказывает услуги по уничтожению насекомых и грызунов
  в Ташкенте. Мы работаем с частными и корпоративными клиентами по высокоэффективной
  Американской системе пест-контроля. За время своей деятельности нашими специалистами
  были выполнены десятки тысяч заказов по дезинфекции в Ташкенте. Компания
  предоставляет оптимальные условия для каждого заказчика.
baseurl: ""
url: "https://stopinsect.uz"


header_title: StopInsect
header_subtitle: уничтожение насекомых в Ташкенте
menu:
   - title: Услуги
     url: "#services"
   - title: Цены
     url: "/prices"
   - title: +998 (90) 950-78-16
     url: "tel:+998909507816"
footer_content: © StopInsect.uz — уничтожение насекомых
social:
   - url: "https://t.me/rus_k2"
     icon: fab fa-telegram
   - url: "https://instagram.com/ruslan_dezinfektor"
     icon: fab fa-instagram
   - url: "mailto:soul198555@gmail.com"
     icon: far fa-envelope

collections:
  posts:
    permalink: '/posts/:title/'


exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- ".git"
- ".idea"
